/* ============================================================================
   analytics-client.js — first-party analytics collection.

   Loaded on every page (see scripts/shared_html.py FOOTER). Responsibilities:
     1. Mint / reuse a session id (sessionStorage) and visitor id (localStorage)
     2. trackEvent() -- fire-and-forget POST that never throws and never blocks
     3. Fire a pageview on load
     4. Instrument existing UI via ONE delegated listener set

   Why delegation instead of per-element handlers: this site is ~4,600 static
   pages generated by scripts/*.py. Adding onclick attributes would mean
   rewriting every file and re-touching them on every future regeneration.
   Delegating from document catches the same clicks, including on the map
   result cards that js/map-hero.js injects at runtime, and stays correct as
   pages are regenerated.

   No cookies, no third-party requests, no PII. Both ids are random values the
   browser generates for itself.
   ============================================================================ */
(function () {
  "use strict";

  var ENDPOINT = "/api/analytics/track";
  var SEARCH_DEBOUNCE_MS = 700;
  var A = window.VBWAnalytics;
  if (!A) return; // js/analytics.js failed to load; fail silent, never break the page

  // ---- identity ------------------------------------------------------------
  function randomId() {
    try {
      if (window.crypto && window.crypto.randomUUID) return window.crypto.randomUUID();
      if (window.crypto && window.crypto.getRandomValues) {
        var b = new Uint8Array(16);
        window.crypto.getRandomValues(b);
        return Array.prototype.map.call(b, function (x) {
          return ("0" + x.toString(16)).slice(-2);
        }).join("");
      }
    } catch (e) { /* fall through */ }
    return "x" + Math.random().toString(36).slice(2) + Date.now().toString(36);
  }

  function stored(store, key) {
    // Private browsing / disabled storage must not break tracking or the page.
    try {
      var v = store.getItem(key);
      if (!v) { v = randomId(); store.setItem(key, v); }
      return v;
    } catch (e) {
      return randomId(); // ephemeral fallback
    }
  }

  var sessionId = stored(window.sessionStorage, "vbw_sid");
  var visitorId = stored(window.localStorage, "vbw_vid");

  // ---- transport -----------------------------------------------------------
  function trackEvent(eventType, extra) {
    try {
      if (!A.isValidEvent(eventType)) return;
      var payload = {
        event_type: eventType,
        path:       location.pathname + location.search,
        referrer:   document.referrer || null,
        session_id: sessionId,
        visitor_id: visitorId
      };
      if (extra) {
        for (var k in extra) {
          if (Object.prototype.hasOwnProperty.call(extra, k) && extra[k] != null) {
            payload[k] = extra[k];
          }
        }
      }
      // keepalive lets the request survive the navigation a click triggers.
      fetch(ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        keepalive: true,
        credentials: "omit"
      })["catch"](function () { /* analytics must never surface an error */ });
    } catch (e) { /* never throw from tracking */ }
  }

  window.vbwTrack = trackEvent; // exposed for any page-specific tracking

  // ---- pageview ------------------------------------------------------------
  // Every page here is a full document load (no client-side router), so one
  // pageview per load is correct. The server promotes this to listing_view on
  // /partners/<slug>/ and /reviews/<slug>/.
  function firePageview() { trackEvent(A.EVENTS.PAGEVIEW); }
  if (document.readyState === "complete" || document.readyState === "interactive") {
    firePageview();
  } else {
    document.addEventListener("DOMContentLoaded", firePageview);
  }

  // ---- helpers -------------------------------------------------------------
  function paramFrom(href, name) {
    try {
      var q = href.indexOf("?");
      if (q === -1) return null;
      return new URLSearchParams(href.slice(q + 1)).get(name);
    } catch (e) { return null; }
  }

  function slugFromPartnerHref(href) {
    var m = /\/(?:partners|reviews)\/([a-z0-9-]+)\/?/i.exec(href || "");
    return m ? m[1] : null;
  }

  // ---- delegated click instrumentation ------------------------------------
  document.addEventListener("click", function (ev) {
    var a = ev.target && ev.target.closest ? ev.target.closest("a") : null;
    if (!a) return;
    var href = a.getAttribute("href") || "";
    if (!href) return;

    // Google review links -> review_click. The listing is whichever profile
    // page the link sits on.
    if (href.indexOf("search.google.com/local/reviews") !== -1) {
      var ctx = A.classifyListingPath(location.pathname);
      trackEvent(A.EVENTS.REVIEW_CLICK, { listing_slug: ctx.listingSlug });
      return;
    }

    // The quote CTA is this site's click-to-call equivalent -- it is the only
    // path to a contractor, since no phone numbers are published anywhere.
    if (href.indexOf("/get-a-quote/") === 0) {
      trackEvent(A.EVENTS.QUOTE_CLICK, {
        listing_slug: paramFrom(href, "provider") ||
                      A.classifyListingPath(location.pathname).listingSlug
      });
      return;
    }

    // Contractor claiming their own listing.
    if (href.indexOf("/claim-listing/") === 0) {
      trackEvent(A.EVENTS.CLAIM_CLICK, {
        listing_slug: paramFrom(href, "provider") ||
                      A.classifyListingPath(location.pathname).listingSlug
      });
      return;
    }

    // A click through to a listing from a card or map result. Recorded against
    // the DESTINATION listing so the per-business table attributes it correctly;
    // the destination page's own pageview is what becomes its listing_view, so
    // this is not double counted.
    if (href.indexOf("/partners/") === 0 || href.indexOf("/reviews/") === 0) {
      var slug = slugFromPartnerHref(href);
      if (slug) trackEvent(A.EVENTS.LISTING_VIEW, { listing_slug: slug });
    }
  }, true);

  // ---- delegated search instrumentation -----------------------------------
  // One debounce timer per input id, so the map ZIP search and the directory
  // table search don't cancel each other.
  var searchTimers = {};
  var TRACKED_SEARCH_INPUTS = { zipInput: "map_zip", dirSearch: "directory" };

  document.addEventListener("input", function (ev) {
    var el = ev.target;
    if (!el || !el.id || !TRACKED_SEARCH_INPUTS[el.id]) return;
    var key = el.id;
    var value = (el.value || "").trim();
    if (searchTimers[key]) clearTimeout(searchTimers[key]);
    if (value.length < 2) return; // ignore incidental single keystrokes
    searchTimers[key] = setTimeout(function () {
      trackEvent(A.EVENTS.SEARCH, { query: value });
    }, SEARCH_DEBOUNCE_MS);
  }, true);

  // The homepage / CTA ZIP bars submit straight to the quote form, so treat
  // the submit as the quote intent it is and carry the ZIP as the query.
  document.addEventListener("submit", function (ev) {
    var form = ev.target;
    if (!form || !form.getAttribute) return;
    var action = form.getAttribute("action") || "";
    if (action.indexOf("/get-a-quote/") !== 0) return;
    var input = form.querySelector('input[name="zip"]');
    trackEvent(A.EVENTS.QUOTE_CLICK, {
      query: input && input.value ? input.value.trim() : null
    });
  }, true);
})();
