#!/usr/bin/env python3
"""Patch static HTML pages that are NOT generated by the generator scripts.
- Remove phone numbers, replace with Submit Job Request CTAs
- Replace old header-phone div with Submit Job Request button in header-right
- Replace footer-phone link with Submit Job Request button
- Remove phone from footer-bottom
- Remove telephone from JSON-LD schema
- Remove emoji icons from mega-menu items
"""
import os, re

ROOT = "/home/user/virginiabasementwaterproofing.com"

STATIC_FILES = []
for path in [
    "services/index.html",
    "about/index.html",
    "privacy-policy/index.html",
    "terms-of-service/index.html",
    "disclaimer/index.html",
    "blog/index.html",
    "blog/does-waterproofing-basement-add-value-to-your-home/index.html",
    "blog/how-does-basement-waterproofing-work/index.html",
    "blog/how-long-does-basement-waterproofing-last/index.html",
    "blog/how-to-dry-a-wet-basement-floor-fast/index.html",
    "blog/how-to-repair-basement-wall-and-floor-cracks/index.html",
    "blog/should-vents-under-house-be-open-or-closed-in-summer/index.html",
    "blog/what-is-a-basement-waterproofing-system/index.html",
    "virginia/index.html",
]:
    full = os.path.join(ROOT, path)
    if os.path.exists(full):
        STATIC_FILES.append(full)

HEADER_RIGHT_OLD = re.compile(
    r'<div class="header-right">\s*'
    r'<div class="header-phone">.*?</div>\s*'
    r'(<button class="nav-toggle"[^>]*>).*?(</button>)\s*'
    r'</div>',
    re.DOTALL
)

def patch_header_right(html):
    def replacer(m):
        return (
            '<div class="header-right">\n'
            '      <a href="tel:+17577202096" class="btn btn--primary header-cta btn--phone"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/></svg><span class="btn--phone__text"><span class="btn--phone__number">757-720-2096</span><span class="btn--phone__sub">Call/Text 24/7</span></span></a>\n'
            '      <button class="nav-toggle" aria-label="Toggle menu" aria-expanded="false" aria-controls="main-nav">&#9776;</button>\n'
            '    </div>'
        )
    return HEADER_RIGHT_OLD.sub(replacer, html)

def patch_footer_phone(html):
    # Replace <a class="footer-phone" href="tel:...">...</a> with Submit Job Request btn
    html = re.sub(
        r'<a class="footer-phone" href="tel:[^"]*">[^<]*</a>',
        '<a href="tel:+17577202096" class="btn btn--primary btn--phone"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/></svg><span class="btn--phone__text"><span class="btn--phone__number">757-720-2096</span><span class="btn--phone__sub">Call or Text 24/7 for Quote</span></span></a>',
        html
    )
    # Replace footer-bottom phone link
    html = re.sub(
        r'<span>Call us:\s*<a href="tel:[^"]*">[^<]*</a></span>',
        '<span><a href="/get-a-quote/">Free Estimate &rarr;</a></span>',
        html
    )
    return html

def patch_inline_phone_text(html):
    # Remove "Prefer to talk now? Call (xxx) xxx-xxxx." type sentences
    html = re.sub(
        r'Prefer to talk now\? Call <a href="tel:[^"]*">[^<]*</a>\.',
        '',
        html
    )
    # Remove standalone phone links in content
    html = re.sub(
        r'<a href="tel:\+17577439050">\(757\) 743-9050</a>',
        '<a href="/get-a-quote/">submit a job request</a>',
        html
    )
    # Remove "Call (757) 743-9050" plain text
    html = re.sub(r'call \(757\) 743-9050', 'submit a job request', html, flags=re.IGNORECASE)
    html = re.sub(r'\(757\) 743-9050', '', html)
    return html

def patch_schema_telephone(html):
    # Remove "telephone" field from JSON-LD
    html = re.sub(r'\s*"telephone":\s*"\+?\d+"[,]?', '', html)
    return html

def patch_emoji_in_mega_menu(html):
    # Remove emoji span from mega-menu items: <span class="mega-menu__icon">...</span>
    html = re.sub(r'<span class="mega-menu__icon">.*?</span>\s*', '', html)
    return html

def patch_map_hero_bar_cta(html):
    # Remove the standalone CTA button from map-hero__bar if still present
    html = re.sub(
        r'\s*<a href="/get-a-quote/" class="btn btn--primary" style="margin-top:14px;">Submit Job Request &mdash; It&rsquo;s Free</a>',
        '',
        html
    )
    html = re.sub(
        r"\s*<a href=\"/get-a-quote/\" class=\"btn btn--primary\" style=\"margin-top:14px;\">Submit a Job Request &mdash; It's Free</a>",
        '',
        html
    )
    return html

patched = 0
for fpath in STATIC_FILES:
    with open(fpath) as f:
        original = f.read()
    html = original
    html = patch_header_right(html)
    html = patch_footer_phone(html)
    html = patch_inline_phone_text(html)
    html = patch_schema_telephone(html)
    html = patch_emoji_in_mega_menu(html)
    html = patch_map_hero_bar_cta(html)
    if html != original:
        with open(fpath, 'w') as f:
            f.write(html)
        print(f"Patched: {fpath.replace(ROOT+'/', '')}")
        patched += 1
    else:
        print(f"No changes: {fpath.replace(ROOT+'/', '')}")

print(f"\nDone — {patched}/{len(STATIC_FILES)} files patched")
